### ISSUE TITLE
strukurera upp wikin lite mer

### ISSUE THREAD

**Issue by hhampush** [hhampush/mopedkursen#4]
kanske kan vara bra att få den lite mer lättnavigerad om burden et al ska in och kika på den sen

**Comment by magnlar** [comment]
Några mer specifika idéer om hur denna strukturering ska gå till?

Spånar lite spontant:
Något slags "katalogstruktur" med i varje fall separation mellan sidor som är relaterat till Scrumprocessen och sådana som är relaterade till kodning

**Comment by hhampush** [comment]
@magnlar ja det låter gott. tänker mig kanske att man kan ha samlingssidor på något sätt, kanske så man kan få bort "subsidor" ur menyn

**Comment by RamiJabor** [comment]
Har samlat ihop guides och projekt/rapportmaterial ock skapat ny sidebar så det är mer organiserat.
